FileVersion = 1
LastConfig = "Release"
LastPlatform = "Win64"
RecentFilesList = ["src\\AverageMethods.bf", "src\\Program2.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\IO\\StreamReader.bf", "src\\Program3.bf", "Disassembly", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf", "src\\Vector3.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\IO\\MemoryStream.bf", "src\\ReplayFrame.bf", "src\\ShavitReplay.bf", "src\\Vector2.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\IO\\Stream.bf"]

[MainWindow]
X = 149
Y = -20
Width = 1200
Height = 1024
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 968.0
RequestedHeight = 400.0
SizePriority = 400.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 268.0
RequestedHeight = 250.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 400.0
SizePriority = 250.0
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "StreamReader.bf"
TabWidth = 137.0
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\IO\\StreamReader.bf"
CursorPos = 8063
VertPos = 4245.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "AverageMethods.bf"
TabWidth = 155.0
Type = "SourceViewPanel"
FilePath = "src\\AverageMethods.bf"
CursorPos = 202
ProjectName = "BeefLangStuff"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program3.bf"
TabWidth = 103.0
Type = "SourceViewPanel"
FilePath = "src\\Program3.bf"
CursorPos = 56
ProjectName = "BeefLangStuff"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Vector2.bf"
TabWidth = 90.0
Type = "SourceViewPanel"
FilePath = "src\\Vector2.bf"
CursorPos = 333
ProjectName = "BeefLangStuff"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Vector3.bf"
TabWidth = 90.0
Type = "SourceViewPanel"
FilePath = "src\\Vector3.bf"
CursorPos = 422
ProjectName = "BeefLangStuff"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "String.bf"
TabWidth = 79.0
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf"
CursorPos = 28612
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 122.0
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ReplayFrame.bf"
TabWidth = 120.0
Type = "SourceViewPanel"
FilePath = "src\\ReplayFrame.bf"
CursorPos = 420
ProjectName = "BeefLangStuff"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ShavitReplay.bf"
TabWidth = 118.0
Type = "SourceViewPanel"
FilePath = "src\\ShavitReplay.bf"
CursorPos = 682
ProjectName = "BeefLangStuff"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program2.bf"
TabWidth = 103.0
Type = "SourceViewPanel"
FilePath = "src\\Program2.bf"
CursorPos = 949
VertPos = 75.0
ProjectName = "BeefLangStuff"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.2190636
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.7809365
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 450.0
RequestedHeight = 250.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]
Items = ["stream.Position", "header", "__clearHighBits(mAllocSizeAndFlags, 2)", "__clearHighBits(mAllocSizeAndFlags, 2)", "ReadFrame", ""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 77.0
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[Breakpoints]]
File = "src\\HeapProperties.bf"
Line = 20
Column = 3
